import type { DashboardDef } from '../types';

/**
 * Token Usage dashboard.
 *
 * Row 1 — 4 KPI cards with colored icons + subtitles (1 unit tall)
 * Row 2 — time series (8 cols) + recent invocations feed (4 cols) (3 units)
 * Row 3 — breakdown by feature (6) + breakdown by model (6) (4 units)
 * Row 4 — breakdown by project (6) + breakdown by user (6) (4 units)
 * Row 5 — full paginated + sortable invocations log (12 cols, 6 units)
 *
 * Breakdown widgets hide themselves when their dimension is already
 * narrowed to a single value.
 */
const tokenUsageDashboard: DashboardDef = {
  slug: 'token-usage',
  title: 'Token Utilization Dashboard',
  category: 'ops',
  filters: ['dateRange', 'projectId', 'modelName', 'feature'],
  layout: [
    // ── Row 1: KPIs ─────────────────────────────────────
    { w: 3, h: 1, widget: {
      type: 'metric', metric: 'tokens.total',
      title: 'Total Tokens',
      subtitle: 'Cumulative input and output tokens',
      icon: 'link', iconColor: 'orange',
    }},
    { w: 3, h: 1, widget: {
      type: 'metric', metric: 'tokens.prompt',
      title: 'Prompt (Input) Tokens',
      subtitle: 'Context & instructions parsed by LLM',
      icon: 'cpu', iconColor: 'blue',
    }},
    { w: 3, h: 1, widget: {
      type: 'metric', metric: 'tokens.completion',
      title: 'Completion (Output) Tokens',
      subtitle: 'Responses generated by LLM',
      icon: 'layers', iconColor: 'green',
    }},
    { w: 3, h: 1, widget: {
      type: 'metric', metric: 'tokens.requests',
      title: 'Total Requests',
      subtitle: 'Total LLM invocations triggered',
      icon: 'activity', iconColor: 'purple',
    }},

    // ── Row 2: time series + model donut + live recent feed ──
    { w: 6, h: 3, widget: {
      type: 'timeseries', metric: 'tokens.timeseries',
      title: 'Token usage over time', stacked: true,
    }},
    { w: 3, h: 3, widget: {
      type: 'donut', metric: 'tokens.by_model',
      title: 'By model',
    }, hideWhen: ['model_name'] },
    { w: 3, h: 3, widget: {
      type: 'table', metric: 'tokens.recent',
      title: 'Recent activity',
      compact: true,
      refetchMs: 3000,                          // refresh faster than default
      columnConfig: {
        timestamp:   { label: 'When',    align: 'left' },
        feature:     { label: 'Feature', align: 'left' },
        user_name:   { label: 'User',    align: 'left' },
        total_tokens:{ label: 'Tokens',  align: 'right', format: 'bold-number' },
      },
    }},

    // ── Row 3: feature + model breakdown tables ────────
    { w: 6, h: 4, widget: {
      type: 'table', metric: 'tokens.breakdown.feature',
      title: 'Breakdown by Feature',
      sortableColumns: ['requests', 'prompt_tokens', 'completion_tokens', 'total_tokens'],
      compact: true,
      columnConfig: {
        feature:            { label: 'Feature',           format: 'feature-icon' },
        requests:           { label: 'Requests' },
        prompt_tokens:      { label: 'Prompt Tokens' },
        completion_tokens:  { label: 'Completion Tokens' },
        total_tokens:       { label: 'Total Tokens' },
      },
    }, hideWhen: ['feature'] },

    { w: 6, h: 4, widget: {
      type: 'table', metric: 'tokens.breakdown.model',
      title: 'Breakdown by Model',
      sortableColumns: ['requests', 'prompt_tokens', 'completion_tokens', 'total_tokens'],
      compact: true,
      columnConfig: {
        model_name:         { label: 'Model Name' },
        requests:           { label: 'Requests' },
        prompt_tokens:      { label: 'Prompt Tokens' },
        completion_tokens:  { label: 'Completion Tokens' },
        total_tokens:       { label: 'Total Tokens' },
      },
    }, hideWhen: ['model_name'] },

    // ── Row 4: project + user breakdown tables ─────────
    { w: 6, h: 4, widget: {
      type: 'table', metric: 'tokens.breakdown.project',
      title: 'Breakdown by Project',
      sortableColumns: ['requests', 'prompt_tokens', 'completion_tokens', 'total_tokens'],
      compact: true,
      columnConfig: {
        project_name:       { label: 'Project' },
        project_code:       { label: 'Code',     format: 'badge' },
        requests:           { label: 'Requests' },
        prompt_tokens:      { label: 'Prompt Tokens' },
        completion_tokens:  { label: 'Completion Tokens' },
        total_tokens:       { label: 'Total Tokens' },
      },
    }, hideWhen: ['project_id'] },

    { w: 6, h: 4, widget: {
      type: 'table', metric: 'tokens.breakdown.user',
      title: 'Breakdown by User',
      sortableColumns: ['requests', 'prompt_tokens', 'completion_tokens', 'total_tokens'],
      compact: true,
      columnConfig: {
        user_name:          { label: 'User' },
        user_email:         { label: 'Email',    format: 'muted' },
        requests:           { label: 'Requests' },
        prompt_tokens:      { label: 'Prompt Tokens' },
        completion_tokens:  { label: 'Completion Tokens' },
        total_tokens:       { label: 'Total Tokens' },
      },
    }, hideWhen: ['user_id'] },

    // ── Row 5: full paginated invocations log ──────────
    { w: 12, h: 6, widget: {
      type: 'table', metric: 'tokens.invocations',
      title: 'Invocations Log',
      sortableColumns: ['timestamp', 'prompt_tokens', 'completion_tokens', 'total_tokens'],
      pageSize: 20,
      columnConfig: {
        timestamp:          { label: 'Timestamp' },
        feature:            { label: 'Feature' },
        model_name:         { label: 'Model' },
        user_name:          { label: 'User' },
        project_name:       { label: 'Project' },
        prompt_tokens:      { label: 'Prompt Tokens' },
        completion_tokens:  { label: 'Completion Tokens' },
        total_tokens:       { label: 'Total Tokens' },
      },
    }},
  ],
};

export default tokenUsageDashboard;
