"""
Generate seed SQL for the test-case-generation dashboard.

Writes testcase_seed.sql. Run this generator once; commit the .sql output.
Produces realistic data: generation runs over 12 months, test cases with
computed test_type / normalized titles / schema_ok flags, deliberate coverage
gaps, and priority drift.

Usage:
    python3 gen_testcase_seed.py > testcase_seed.sql
"""
import random
import uuid
from datetime import datetime, timedelta

random.seed(42)

PROJECTS = [
    ("Stellar Odyssey", "STLR"),
    ("Lumina", "LUM"),
    ("Nova Realms", "NOVA"),
    ("Pixel Quest", "PXQ"),
    ("Micoprose", "MICR"),
]

USERS = [
    ("Admin User", "admin@indium.tech"),
    ("John Tester", "john.tester@indium.tech"),
    ("Sarah QA", "sarah.qa@indium.tech"),
    ("Miguel Reyes", "miguel.reyes@indium.tech"),
    ("Aisha Khan", "aisha.khan@indium.tech"),
]

MODELS = ["qwen2.5:14b-instruct", "granite4.1:8b", "gpt-4", "claude-3-sonnet"]

# Feature → assigned priority (mirrors the prototype's "assigned" map).
FEATURES = {
    "Combat System": "Core", "Save/Load": "Core", "Matchmaking": "Core",
    "Player Movement": "Core", "Inventory Management": "High",
    "Progression & Leveling": "High", "In-App Purchases": "High",
    "Tutorial & Onboarding": "High", "Achievements": "Medium",
    "Friends & Social": "Medium", "Leaderboards": "Medium",
    "Daily Rewards": "Medium", "Cosmetic Customization": "Low",
    "Emotes & Chat": "Low", "Settings Menu": "Low",
    "Clan/Guild System": "High", "Battle Pass": "Medium",
}

# Features that get ZERO cases → coverage gaps (prioritized but untested).
GAP_FEATURES = {"Clan/Guild System", "Battle Pass"}

COVERAGE = ["Essential", "Standard", "Comprehensive"]
PRIORITIES = ["Core", "High", "Medium", "Low"]

# Title templates by test_type — lets us both generate realistic titles
# and know the ground-truth type (the dashboard re-derives it heuristically).
TITLE_BANK = {
    "happy_path": [
        "Verify {x} works as expected", "Confirm {x} succeeds",
        "Validate {x} completes correctly", "Ensure {x} functions properly",
    ],
    "negative": [
        "Confirm {x} rejects invalid input", "Verify {x} shows an error on failure",
        "Ensure {x} fails gracefully", "Check {x} blocks unauthorized action",
    ],
    "boundary": [
        "Validate {x} at the maximum limit", "Verify {x} at the minimum threshold",
        "Confirm {x} handles the boundary value", "Check {x} at capacity",
    ],
    "error_handling": [
        "Ensure {x} recovers from a crash", "Verify {x} handles corrupted data",
        "Confirm {x} falls back after timeout", "Check {x} restores after force-quit",
    ],
}

SUBJECTS = [
    "the feature", "the action", "the transition", "the state", "the sync",
    "the update", "the reset", "the unlock", "the purchase", "the match",
]

# Keyword → test_type, the HEURISTIC the dashboard uses. Mirrors reality: ~85%.
def classify_test_type(title: str) -> str:
    t = title.lower()
    if any(w in t for w in ["reject", "invalid", "error", "fails", "fail ", "blocks", "unauthorized"]):
        return "negative"
    if any(w in t for w in ["maximum", "minimum", "limit", "boundary", "threshold", "capacity"]):
        return "boundary"
    if any(w in t for w in ["crash", "corrupted", "timeout", "force-quit", "recover", "restore", "fall"]):
        return "error_handling"
    return "happy_path"

# Verb-stripping normalizer for duplicate detection.
LEADING_VERBS = ["verify", "validate", "confirm", "ensure", "check", "test"]
def normalize_title(title: str) -> str:
    t = title.lower().strip()
    for v in LEADING_VERBS:
        if t.startswith(v + " "):
            t = t[len(v) + 1:]
            break
    return t

def esc(s: str) -> str:
    return s.replace("'", "''")

# ── generate ────────────────────────────────────────────────────────────────

print("-- Auto-generated by gen_testcase_seed.py. Do not edit by hand.")
print("TRUNCATE TABLE test_cases;")
print("TRUNCATE TABLE generation_runs CASCADE;")
print("TRUNCATE TABLE tc_feature_priorities;")
print("TRUNCATE TABLE tc_users CASCADE;")
print("TRUNCATE TABLE tc_projects CASCADE;")
print()

project_ids = {name: str(uuid.uuid4()) for name, _ in PROJECTS}
user_ids = [str(uuid.uuid4()) for _ in USERS]

# Projects
print("INSERT INTO tc_projects (id, name, code) VALUES")
print(",\n".join(f"  ('{project_ids[n]}', '{esc(n)}', '{c}')" for n, c in PROJECTS) + ";")
print()

# Users
print("INSERT INTO tc_users (id, name, email) VALUES")
print(",\n".join(f"  ('{user_ids[i]}', '{esc(n)}', '{e}')" for i, (n, e) in enumerate(USERS)) + ";")
print()

# Feature priorities (every feature, every project gets the assigned tier)
fp_rows = []
for pname in project_ids:
    for feat, prio in FEATURES.items():
        fp_rows.append(f"  ('{project_ids[pname]}', '{esc(feat)}', '{prio}')")
print("INSERT INTO tc_feature_priorities (project_id, feature, assigned_priority) VALUES")
print(",\n".join(fp_rows) + ";")
print()

now = datetime.utcnow()
run_rows = []
case_rows = []

# Generate ~250 runs over 12 months.
for _ in range(250):
    run_id = str(uuid.uuid4())
    pname = random.choice(list(project_ids))
    pid = project_ids[pname]
    uid = random.choice(user_ids)
    coverage = random.choices(COVERAGE, weights=[0.3, 0.45, 0.25])[0]
    model = random.choice(MODELS)
    # Skew toward recent.
    days_ago = (random.random() ** 1.5) * 365
    created = now - timedelta(days=days_ago, hours=random.randint(0, 23))

    # How many features this run covers (subset of the real features).
    testable = [f for f in FEATURES if f not in GAP_FEATURES]
    n_features = random.randint(3, 8)
    run_features = random.sample(testable, min(n_features, len(testable)))

    features_extracted = len(run_features) + random.randint(0, 3)
    features_prioritized = len(run_features)

    # Cases per feature scale with coverage level.
    cov_mult = {"Essential": (1, 3), "Standard": (3, 6), "Comprehensive": (5, 9)}[coverage]

    parse_failures = 0
    run_case_count = 0

    for feat in run_features:
        assigned = FEATURES[feat]
        n_cases = random.randint(*cov_mult)
        for _ in range(n_cases):
            # ~8% priority drift: case priority differs from feature's assigned tier.
            if random.random() < 0.08:
                prio = random.choice([p for p in PRIORITIES if p != assigned])
            else:
                prio = assigned

            ttype_truth = random.choices(
                list(TITLE_BANK), weights=[0.62, 0.16, 0.12, 0.10]
            )[0]
            title = random.choice(TITLE_BANK[ttype_truth]).format(x=random.choice(SUBJECTS))

            # ~6% schema failures: empty steps / missing fields (parse issues).
            schema_bad = random.random() < 0.06
            if schema_bad:
                steps = []
                step_count = 0
                preconditions = "" if random.random() < 0.5 else "Game is running."
                expected = "" if random.random() < 0.5 else "Behaves correctly."
                schema_ok = False
                parse_failures += 1
            else:
                step_count = random.randint(2, 7)
                steps = [f"Step {i+1}" for i in range(step_count)]
                preconditions = "Game is running and player is logged in."
                expected = "The system behaves according to the design spec."
                schema_ok = True

            title_norm = normalize_title(title)
            test_type = classify_test_type(title)   # heuristic, may differ from truth
            steps_json = "'" + esc(str(steps).replace("'", '"')) + "'::jsonb" if steps else "'[]'::jsonb"
            tc_id = f"TC-{run_case_count+1:03d}"

            case_rows.append(
                f"  ('{run_id}', '{tc_id}', '{esc(feat)}', '{prio}', '{assigned}', "
                f"'{esc(title)}', '{esc(title_norm)}', "
                f"{'NULL' if not preconditions else chr(39)+esc(preconditions)+chr(39)}, "
                f"{steps_json}, {step_count}, "
                f"{'NULL' if not expected else chr(39)+esc(expected)+chr(39)}, "
                f"'{test_type}', '{coverage}', {str(schema_ok).upper()}, "
                f"'{created.isoformat()}')"
            )
            run_case_count += 1

    # Run status from parse failures.
    if run_case_count == 0:
        status = "failed"
    elif parse_failures > 0:
        status = "partial"
    else:
        status = "success"

    duration = random.randint(4000, 45000)
    run_rows.append(
        f"  ('{run_id}', '{pid}', '{uid}', '{coverage}', '{model}', "
        f"{features_extracted}, {features_prioritized}, {run_case_count}, "
        f"{parse_failures}, '{status}', {duration}, "
        f"'{created.isoformat()}')"
    )

# A few fully-failed runs (0 cases) for the failed-run KPI.
for _ in range(6):
    run_id = str(uuid.uuid4())
    pname = random.choice(list(project_ids))
    days_ago = (random.random() ** 1.5) * 365
    created = now - timedelta(days=days_ago)
    run_rows.append(
        f"  ('{run_id}', '{project_ids[pname]}', '{random.choice(user_ids)}', "
        f"'Standard', '{random.choice(MODELS)}', {random.randint(3,6)}, 0, 0, "
        f"{random.randint(1,4)}, 'failed', {random.randint(2000,8000)}, "
        f"'{created.isoformat()}')"
    )

print("INSERT INTO generation_runs (id, project_id, reported_by, coverage_level, model,")
print("    features_extracted, features_prioritized, test_cases_generated,")
print("    parse_failures, status, duration_ms, created_at) VALUES")
print(",\n".join(run_rows) + ";")
print()

print("INSERT INTO test_cases (run_id, test_case_id, feature, priority, assigned_priority,")
print("    title, title_normalized, preconditions, steps, step_count, expected_result,")
print("    test_type, coverage_level, schema_ok, created_at) VALUES")
print(",\n".join(case_rows) + ";")
print()

print("SELECT")
print("    (SELECT COUNT(*) FROM generation_runs) AS runs,")
print("    (SELECT COUNT(*) FROM test_cases)       AS cases,")
print("    (SELECT COUNT(*) FROM test_cases WHERE NOT schema_ok) AS schema_fails,")
print("    (SELECT COUNT(*) FROM test_cases WHERE priority <> assigned_priority) AS drift,")
print("    (SELECT COUNT(DISTINCT feature) FROM test_cases) AS features_tested;")
